// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	R2: R2Bucket;
	DB: D1Database;
	CWBlurhash: Fetcher;
	CWImageCaption: Fetcher;
	Q: Queue;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
