// Generated by Wrangler by running `wrangler types`

interface Env {
	R2: R2Bucket;
	DB: D1Database;
	CWBlurhash: Fetcher;
	CWImageCaption: Fetcher;
	Q: Queue;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
